//
// Created by Vinovrski Alexandre on 09/02/2024.
//

#ifndef TOKENTYPE_H
#define TOKENTYPE_H

enum class TokenType {
    HEADER1,
    HEADER2,
    HEADER3,
    HEADER4,
    HEADER5,
    HEADER6,
    BOLDITALIC,
    BOLD,
    ITALIC,
    STRIKETHROUGH,
    UNORDERED_LIST,
    ORDERED_LIST,
    CHECKLISTCHECKED,
    CHECKLISTUNCHECKED,
    BLOCKQUOTE,
    INLINE_CODE,
    HORIZONTAL_RULE,
    ESCAPE_CHARACTER,
    PARAGRAPH,
    CODE_BLOCK,
    TABLE,
    FOOTNOTE,
    HIGHLIGHT,
    LINKS,
    IMAGES,
};

#endif //TOKENTYPE_H
